version: '3.7'
services:
  drf:
    build: ./django-rest
    ports:
      - "8001:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
  fastapi:
    build: ./fastapi-rest
    ports:
      - "8002:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
  robyn:
    build: ./robyn-rest
    ports:
      - "8003:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
  actix-web:
    build: ./actix-web-rest
    ports:
      - "8004:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
