run:
	cd apiexample && ./manage.py runserver

make-migrations:
	cd apiexample && ./manage.py makemigrations apiexample

migrate:
	cd apiexample && ./manage.py migrate

format-and-lint:
	ruff format . && ruff check .